# Generated by Django 4.2.2 on 2023-06-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('patrimonio', models.CharField(max_length=50)),
                ('sistema', models.CharField(max_length=50)),
            ],
        ),
    ]
