# Generated by Django 4.2.2 on 2023-06-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinas',
            name='sistema',
            field=models.CharField(choices=[('Windows 7', 'Windows 7'), ('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11')], max_length=50),
        ),
    ]
