# Generated by Django 4.2.2 on 2023-06-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_maquinas_sistema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maquinas",
            name="sistema",
            field=models.CharField(
                choices=[
                    ("Windows 7", "Windows 7"),
                    ("Windows 10", "Windows 10"),
                    ("Windows 11", "Windows 11"),
                    ("Server", "Server"),
                ],
                max_length=50,
            ),
        ),
    ]
